### ISSUE TITLE
eBPF maybe?

### ISSUE THREAD

**Issue by moldabekov** [osandov/drgn#18]
Hello, just found your project while browsing LKML on new memory slab manager. 

After looking into dragon I am curious. Have you heard anything about eBPF? I just want to understand what drgn can do, what eBPF can't? Isn't it a better option to put your priceless effort into [bcc project](https://github.com/iovisor/bcc)?

It's just a suggestion, not any kind of criticism.

**Comment by osandov** [comment]
I'm a big fan of tracing with BPF, and I've used BCC quite a bit for debugging. However, the ways BCC and drgn work under the hood are completely different, which means that they're good at different things. BPF is perfect for live tracing, like if you have a function that you want to watch calls to. However, the safety limitations on BPF mean that it can't, for example, traverse complicated data structures. And, of course, it can't help you at all if all you have is a crash dump.

drgn is instead well-suited for introspecting arbitrary data structures post-mortem on a live or crashed kernel. It's all done from userspace, so there are no restrictions on what your script can do. But because it's done outside of the kernel, it can't capture events as they happen like BPF can.

I think there's potential for making use of both drgn and BPF for some use cases (e.g., by defining a "breakpoint" with BPF that runs a drgn script to do the heavy lifting), but for now they're two fundamentally different ways of debugging.
