### ISSUE TITLE
address_of_() doesn't work with gendisk iterated by for_each_disk()

### ISSUE THREAD

**Issue by darengithub** [osandov/drgn#191]
I am running the code
```
 38 def get_gendisk_by_name(name, tryit=False):
 39     for gendisk in for_each_disk(prog):
 40         addr = gendisk.address_of_()
 41         if gendisk.disk_name.string_().decode() == name:
 42             return gendisk
 43     if tryit:
 44         return None
 45     warn("Block device with name %s is not found" % name)
 46     raise
```

and got the following error:
```
  File "/work/drgn/myio.py", line 59, in cmd_gendisk
    gendisk = get_gendisk_by_name(name, tryit = True)
  File "/work/drgn/myio.py", line 40, in get_gendisk_by_name
    addr = gendisk.address_of_()
ValueError: cannot take address of value
```

Verified the type of gendisk is:
<class '_drgn.Object'>

**Comment by brenns10** [comment]
To add onto the above - the exact error you're seeing here stems from the difference between "reference" and "value" objects in drgn, which you can read more about [here](https://drgn.readthedocs.io/en/latest/user_guide.html#objects), up through the next section "References vs Values". You can take the address of a reference object because it resides somewhere in the kernel memory. You can't take the address of a value object because it's just a computed value outside of kernel memory.

There are two versions of for_each_disk() depending on the kernel version. [One](https://github.com/osandov/drgn/blob/main/drgn/helpers/linux/block.py#L92) returns "references" to a `struct gendisk *`, and the [other](https://github.com/osandov/drgn/blob/main/drgn/helpers/linux/block.py#L96) returns "values". As Omar said this shouldn't matter since you care about the `struct gendisk *`.

**Comment by darengithub** [comment]
Hi!
Yes, the .value_() method works in this case.

Well, I am wondering if it would be better to have a unified interface to get the address of the structure in the virtual space in the core.   So that we don't have to be clear with the structures are actually "reference" objects or "value" objects. Actually I don't care what they are, "reference" or "value". I care the addresses of them and the members in them.
In my real code, I am passing various object to a function which prints some common information about the object passed in. The address is one thing I print in that function.  That code was working well with "reference" objects until I passed in the "gendisk" returned by for_each_disk().  To make it work with both "reference" objects and "value" ones, I have to change it like this:

```
 81     addr_ = structure.address_
 82     if addr_ is None:
 83         addr_ = structure.value_()
 84
```

What is confusing me is that the value_() method is returning the address of "value" object. So I don't understand why it's said that "You can't take the address of a value object"?   For this case, the gendisk are actually something exist the inside kernel memory objects, right?  What's the benefit of returning "value" objects?

Hm... I almost care only the "reference" Objects and don't need "value" ones.  To me, the "reference" objects can do all things that "value" objects do, is that right?  So in what case we need the "value" objects?  In what cases we need objects outside of kernel memory? examples? 

It's also confusing me that the same interface of for_each_disk() has different type of the returned objects for different kernel versions.  If I want to use the exact same script for different kernel versions, I have to use different methods to get the addresses according to kernel version. That's not hard, but boring, people have to pay time to take care of those.

Grgn is great! I am new to drgn, maybe my understanding is wrong here.

**Comment by osandov** [comment]
Let's forget about drgn for a second and just think of it in terms of C. From what I understand, you want to print the address of the `struct gendisk` in memory. If you have a `struct gendisk *` pointer, then the value of that pointer _is_ the address of the `struct gendisk` (i.e., the pointer itself is more or less an integer address).

Going back to drgn, `for_each_disk()` yields a `struct gendisk *` object. That `gendisk` object represents a pointer, and `gendisk.value_()` returns the value of the pointer. Forget about references and values for now, because regardless of whether the object is a reference or a value under the hood, `gendisk.value_()` returns the pointer value, which _is_ the address of the `struct gendisk` that it points to and thus what you want to print.

`gendisk.address_` and `gendisk.address_of_()` aren't what you wanted in the first place. That's not the address of the structure; that's the address of the _pointer to the structure_. It'd be like doing the following in C:

```c
struct gendisk *disk = ...;
printk("%p\n", &disk); // Wrong, this prints a pointer to a pointer!
```

When what you actually want is this:

```c
struct gendisk *disk = ...;
printk("%p\n", disk);
```

**So, for this use case, always use `gendisk.value_()`; `gendisk.address_` and `gendisk.address_of_()` aren't what you want.**

References and values are a tricky part of the drgn API that I've struggled to document clearly enough, so I'll try to explain a bit more here. As a user, the main thing you usually care about is the object's type at the C level (`struct foo`, `void *`, etc.). Whether it is a reference or a value, it will behave according to its C type. The concept of reference objects and value objects operates at a lower level. There are lots of examples of value objects, but the simplest one is if I did something like this:

```pycon
>>> num = prog["my_num"]
>>> num_plus_one = num + 1
```

`num` is a variable in the program's memory, so it is a reference object. However, `num_plus_one` is a computed value that doesn't exist in the program's memory, so it can't be a reference object. Any computation like that will create a value object.

`for_each_disk()` returrns a reference object for some kernels because in those versions, the `struct gendisk *` is stored as a member in some other structure, so the pointer itself exists in memory. On other kernel versions, the `struct gendisk *` is computed with `container_of()` from another pointer, so the `struct gendisk *` doesn't exist in the kernel's memory and must be a value object. This wasn't a conscious decision; it was just the natural result of how the data structures work and how the helper was implemented. As I noted above, it shouldn't actually matter for you; just use `gendisk.value_()` unconditionally.

**Comment by darengithub** [comment]
Thanks Omar for the explaining!

So the address_ and address_of_() are strictly returning something like & operator in C, I got it.  It seems equal to the "Deref" method in pykdump.   I am actually seeking something like "Addr" method in pykdump.  Addr() is anyway returning the address of the structure its self, it behaves like this:
```
if type of object is "struct xxxx *p":
     return (int)p
elif type of object is "struct xxxx p":
    return &p
....
```
 
It seems that there is no equivalent in drgn.  The value_() doesn't work on all objects.
the code is like this:
```
 84     print("type of structure", type(structure))
 85     addr_ = structure.value_()
 86     print("type of addr_", type(addr_))
 87     print("addr_", addr_)
```
and got this:
```
ype of structure <class '_drgn.Object'>
type of addr_ <class 'dict'>
addr_ {'q_dmadev': 18446615483861057696, 'dev': 18446615758264369152, 'sq_lock': {'rlock': {'raw_lock': {'val': {'counter': 0}, 'locked': 0, 'pending': 0, 'locked_pending': 0, 'tail': 0}}}, 'sq_cmds': 18446615758225276928, 'sq_cmds_io': 0, 'cq_lock': {'rlock': {'raw_lock': {'val': {'counter': 0}, 'locked': 0, 'pending': 0, 'locked_pending': 0, 'tail': 0}}}, 'cqes': 18446615758225227776, 'tags': 18446615758225213952, 'sq_dma_addr': 410054295552, 'cq_dma_addr': 410054246400, 'q_db': 18446628138799640584, 'q_depth': 1024, 'cq_vector': 1, 'sq_tail': 67, 'cq_head': 143, 'last_cq_head': 143, 'qid': 1, 'cq_phase': 1, 'dbbuf_sq_db': 0, 'dbbuf_cq_db': 0, 'dbbuf_sq_ei': 0, 'dbbuf_cq_ei': 0}
```
For the object passed in as "structure", it's created like this:
`nvme_queue = Object(prog, "struct nvme_queue", address = xxxx)`
the address was a valid address.
So the value_() doesn't work in above example.

For your value object example of num = prog["my_num"],
If it's just a number, I'd would rather just use the integer type in Python. Maybe you don't like the Python integer especially when process "unsigned" ones. 

For the for_each_disk() explanation, I can't really agree with you.  container_of() is taking an address as input and do a minus operation (offset) to that address to get a new address and read the data for the container structure from the new address.  The new address is still a valid address in kernel memory. So I can't agree that the returned structure doesn't exist in kernel memory.

**Comment by osandov** [comment]
> Thanks Omar for the explaining!
> 
> So the address_ and address_of_() are strictly returning something like & operator in C, I got it. It seems equal to the "Deref" method in pykdump. I am actually seeking something like "Addr" method in pykdump. Addr() is anyway returning the address of the structure its self, it behaves like this:
> 
> ```
> if type of object is "struct xxxx *p":
>      return (int)p
> elif type of object is "struct xxxx p":
>     return &p
> ....
> ```
> 
> It seems that there is no equivalent in drgn.

Correct, drgn doesn't have anything like that. It expects you to know whether you're working with a pointer or a structure and use the appropriate method.

> The value_() doesn't work on all objects. the code is like this:
> 
> ```
>  84     print("type of structure", type(structure))
>  85     addr_ = structure.value_()
>  86     print("type of addr_", type(addr_))
>  87     print("addr_", addr_)
> ```
> 
> and got this:
> 
> ```
> ype of structure <class '_drgn.Object'>
> type of addr_ <class 'dict'>
> addr_ {'q_dmadev': 18446615483861057696, 'dev': 18446615758264369152, 'sq_lock': {'rlock': {'raw_lock': {'val': {'counter': 0}, 'locked': 0, 'pending': 0, 'locked_pending': 0, 'tail': 0}}}, 'sq_cmds': 18446615758225276928, 'sq_cmds_io': 0, 'cq_lock': {'rlock': {'raw_lock': {'val': {'counter': 0}, 'locked': 0, 'pending': 0, 'locked_pending': 0, 'tail': 0}}}, 'cqes': 18446615758225227776, 'tags': 18446615758225213952, 'sq_dma_addr': 410054295552, 'cq_dma_addr': 410054246400, 'q_db': 18446628138799640584, 'q_depth': 1024, 'cq_vector': 1, 'sq_tail': 67, 'cq_head': 143, 'last_cq_head': 143, 'qid': 1, 'cq_phase': 1, 'dbbuf_sq_db': 0, 'dbbuf_cq_db': 0, 'dbbuf_sq_ei': 0, 'dbbuf_cq_ei': 0}
> ```
> 
> For the object passed in as "structure", it's created like this: `nvme_queue = Object(prog, "struct nvme_queue", address = xxxx)` the address was a valid address. So the value_() doesn't work in above example.

Right, this object represents a structure and not a pointer, so `nvme_queue.value_()` gets the value of the structure itself (as a dictionary). This is a case where you would want `nvme_queue.address_`. As I mentioned, you do have to know whether you're working with a structure or a pointer to a structure, just like when you're writing C.

> For your value object example of num = prog["my_num"], If it's just a number, I'd would rather just use the integer type in Python. Maybe you don't like the Python integer especially when process "unsigned" ones.
>
> For the for_each_disk() explanation, I can't really agree with you. container_of() is taking an address as input and do a minus operation (offset) to that address to get a new address and read the data for the container structure from the new address. The new address is still a valid address in kernel memory. So I can't agree that the returned structure doesn't exist in kernel memory.

The `struct gendisk` **structure** exists in kernel memory, yes. But the `struct gendisk *` **pointer** does not.

Here's a longer example. Let's get a reference object representing a `struct inode *`:

```pycon
>>> inode_ptr = prog['init_fs'].root.dentry.d_inode
>>> print(repr(inode_ptr))
Object(prog, 'struct inode *', address=0xffff888113e44630)
>>> print(hex(inode_ptr.value_())
0xffff88811cdb0238
```

There are two addresses here. 0xffff88811cdb0238 is the value of the `struct inode *` pointer, which is the address of the `struct inode` structure that it points to. If we read from that address, we'll see that it corresponds to the contents of the `struct inode` structure:

```pycon
>>> inode_ptr
*(struct inode *)0xffff88811cdb0238 = {
        .i_mode = (umode_t)16877,
        .i_opflags = (unsigned short)10,      
        ...
}
>>> prog.read(0xffff88811cdb0238, 4).hex()
'ed410a00'
>>> hex(16877)
'0x41ed'
>>> hex(10)
'0xa'
```

0xffff888113e44630 is the address of the `struct inode *` pointer itself. If we read from that address, we'll see the value of the pointer (little-endian, of course):

```pycon
>>> prog.read(0xffff888113e44630, 8).hex()
'3802db1c8188ffff'
```

That address came from the structure containing this `struct inode *` pointer:

```pycon
>>> prog['init_fs'].root.dentry
*(struct dentry *)0xffff888113e44600 = {
        ...
        .d_inode = (struct inode *)0xffff88811cdb0238,
        ...
}
>>> offsetof(prog.type("struct dentry"), "d_inode")
48
>>> hex(0xffff888113e44600 + 48)
'0xffff888113e44630'
```

So we can see that the `struct inode *` pointer exists in memory. But now let's call `container_of()`:

```pycon
>>> binode_ptr = container_of(inode_ptr, "struct btrfs_inode", "vfs_inode")
>>> print(repr(binode_ptr))
Object(prog, 'struct btrfs_inode *', value=0xffff88811cdb0000)
```

`container_of()` did a computation with the value of `inode_ptr`, so it has to be a value object, because `binode_ptr` _doesn't exist in kernel memory_. The `struct btrfs_inode` structure does, and I can read from 0xffff88811cdb0000 to read its contents, but as far as we know, there's no address we can read from that will give us back the bytes "0000db1c8188ffff".

**Comment by darengithub** [comment]
OK, so I have to identify if the passed in object is of type "struct xxx" or it's of type "struct yyy *".  For the former, I need to call the address_() or address_of_() to get the memory address of that structure; for the later, call value_().

For your example of container_of(), I understand if the "value" is 0000db1c8188ffff that's not really in memory(so we can't get that).  What my point is that do we really need such a "fake"(not in memory) structure with the value of  0000db1c8188ffff.

**Comment by osandov** [comment]
I think this is resolved. Please reopen or open a new issue if you have more questions.
